version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "doing nothing"
      
  build:
    commands:
      - echo "Zipping deployment package..."
      
      - 
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - 
      - echo "DONE!!"